# Generated by Django 5.0.9 on 2024-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('country', models.CharField(max_length=25, verbose_name='Страна')),
                ('town', models.CharField(max_length=25, verbose_name='Город')),
                ('street', models.CharField(max_length=25, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=25, verbose_name='Номер дома')),
                ('level_company', models.IntegerField(default=25, verbose_name='Уровень компании')),
                ('type_company', models.CharField(choices=[('factory', 'завод'), ('retail_chain', 'розничная сеть'), ('individual_entrepreneur', 'индивидуальный предприниматель')], max_length=25, verbose_name='Тип компании')),
                ('supplier_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя поставщика')),
                ('supplier_id', models.IntegerField(blank=True, null=True, verbose_name='id поставщика')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя поставщика')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='задолженность')),
                ('release', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('customer', models.IntegerField(verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
    ]
